// SPDX-FileCopyrightText: Copyright (c) The helly25 authors (helly25.com)
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef MBO_HASH_HASH_MANGLE_H_
#define MBO_HASH_HASH_MANGLE_H_

// The build-seed mangle: `GetHash` / `MangledHasher` equal `GetHash64` XORed
// with ONE build-selected constant, so values deliberately do not compare
// across independently configured builds - precomputed tables or persisted
// values cannot silently become load-bearing. Everything stays constexpr: the
// constant is generated into a header (`hash_mangle_seed_gen.h`) by folding
// the module's own version (from MODULE.bazel via `native.module_version()` -
// every release rotates the constant by construction, for free: a release
// recompiles dependents anyway) with the custom Bazel flags
//
//   --//mbo/hash:mangle_seed          any printable-ASCII string (user name,
//                                     release tag, date, ...), folded to a
//                                     bucket inside the generation rule
//   --//mbo/hash:mangle_seed_buckets  0 disables (`GetHash == GetHash64`),
//                                     1 pins one stable constant across
//                                     releases and seeds,
//                                     N bounds variation to N constants
//
// Neither the raw seed string nor the version ever reaches a C++ action key,
// so build/remote caches see at most N + 1 header variants and converge no
// matter how often the seed rotates. Only `//mbo/hash:hash_mangle_cc`
// dependents rebuild on rotation; `hash.h` / `//mbo/hash:hash_cc` values are
// fully deterministic and never exposed to seed variation. One constant
// applies per program: linking objects compiled under different flag values
// is an ODR violation (within a single Bazel build consistency is structural
// - there is one generated header per configuration).

#include <cstdint>
#include <string_view>

#include "mbo/hash/hash.h"

// The build-selected constant lives in a header generated per build by
// `//mbo/hash:hash_mangle_seed_gen` (from the module version and the
// `--//mbo/hash:mangle_seed*` flags); it is never committed. A real build that
// lacks it is an error, not a silent fallback. clangd has no generated header,
// so under `-DIS_CLANGD` (set in the clangd config) it falls back to a stable
// constant purely so this low-level header still parses in the editor.
#if __has_include("mbo/hash/hash_mangle_seed_gen.h")
# include "mbo/hash/hash_mangle_seed_gen.h"  // IWYU pragma: export
#elif defined(IS_CLANGD)
namespace mbo::hash {
// The buckets=1 "one stable constant" value (see internal/hash_mangle_seed.bzl).
inline constexpr uint64_t kMangleConstant = 0x45828334C99AF44FULL;
}  // namespace mbo::hash
#else
# error "mbo/hash/hash_mangle_seed_gen.h is missing; it is generated by //mbo/hash:hash_mangle_seed_gen."
#endif

namespace mbo::hash {

// XORs the build-selected mangle constant into `data` (identity when built
// with `--//mbo/hash:mangle_seed_buckets=0`). An XOR mask is deliberately
// trivial to strip - the mangle guards against accidental dependence on hash
// values, not against adversaries (for that see `siphash` with a secret seed).
inline constexpr uint64_t HashMangle(uint64_t data) noexcept {
  return data ^ kMangleConstant;
}

// As `GetHash64` but folded through `HashMangle`, so values **may** change
// between differently configured builds (see the flags above). Use `GetHash`
// when values must deliberately not be comparable across independent builds;
// use `GetHash64` / `GetHash128` for fully deterministic, reproducible values.
template<IsHashAlgorithm Algo = DefaultHashAlgorithm, uint64_t Seed = kDefaultSeed>
constexpr uint64_t GetHash(std::string_view data) noexcept {
  return HashMangle(Hasher<Algo>::GetHash64(data, Seed));
}

// `Hasher<Algo>` extended with the mangled `GetHash`; the functor form applies
// the mangle as well (the inherited deterministic interface remains available).
template<IsHashAlgorithm Algo>
struct MangledHasher : Hasher<Algo> {
  using is_transparent = void;  // NOLINT(readability-identifier-naming): STL heterogeneous-lookup protocol name.

  constexpr uint64_t operator()(std::string_view data) const noexcept { return GetHash(data); }

  static constexpr uint64_t GetHash(std::string_view data, uint64_t seed = kDefaultSeed) noexcept {
    return HashMangle(Hasher<Algo>::GetHash64(data, seed));
  }
};

using DefaultMangledHasher = MangledHasher<DefaultHashAlgorithm>;

}  // namespace mbo::hash

#endif  // MBO_HASH_HASH_MANGLE_H_
