// SPDX-FileCopyrightText: Copyright (c) The helly25 authors (helly25.com)
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generator for `hash_test_vectors.inc`: the known-answer vectors for the
// in-house mumbo/jumbo and dumbo hashes, emitted as ONE field-named constexpr
// struct array (reads like textproto/JSON, but stays a compile-time C++ header
// - no runtime parser, no dependency). The .inc is committed; regenerate it
// INTENTIONALLY when an algorithm changes, then refresh the checksum sidecar:
//   bazel run //mbo/hash:hash_test_vectors_gen > mbo/hash/hash_test_vectors.inc
//   bazel run //mbo/digest:digest -- -a sha256 mbo/hash/hash_test_vectors.inc \
//       > mbo/hash/hash_test_vectors.inc.sha256
// then review the diff (a value change should be a deliberate act). The
// committed .sha256 is an independently verifiable integrity check
// (`sha256sum -c` or `digest --check`); hash_test.cc verifies each vector
// against the live algorithm.

#include <array>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <string>

#include "mbo/hash/hash.h"
#include "mbo/strings/indent.h"

// A one-shot codegen tool: printf is the natural output.
// NOLINTBEGIN(*-vararg,cert-err33-c,*-magic-numbers)

namespace {

// Deterministic input matching hash_test.cc's PatternBuffer: byte i = (i*131+7) % 256.
std::string PatternBuffer(std::size_t len) {
  std::string result(len, '\0');
  for (std::size_t i = 0; i < len; ++i) {
    result[i] = static_cast<char>(((i * 131) + 7) % 256);
  }
  return result;
}

// Lengths span every dispatch tier: small-key (<=16), the sequential chain
// (17..127), and the bulk window (>=128).
constexpr std::array<std::size_t, 13> kLens = {0, 1, 3, 7, 8, 15, 16, 17, 32, 33, 64, 128, 256};
constexpr std::array<std::uint64_t, 2> kSeeds = {0, 5'381};

// Emits the rows for one algorithm (grouped, seed-outer / length-inner).
void EmitAlgo(const char* enumerator, int algo_index) {
  for (const std::uint64_t seed : kSeeds) {
    for (const std::size_t len : kLens) {
      const std::string data = PatternBuffer(len);
      std::uint64_t low = 0;
      std::uint64_t high = 0;
      switch (algo_index) {
        case 0: low = mbo::hash::mumbo::GetHash64(data, seed); break;
        case 1: {
          const mbo::hash::Hash128 hash = mbo::hash::jumbo::GetHash128(data, seed);
          low = hash.h1;
          high = hash.h2;
          break;
        }
        case 2: low = mbo::hash::dumbo::GetHash64(data, seed); break;
        default: break;
      }
      std::printf(
          "    {.algo = Algo::%s, .seed = %lluULL, .len = %zu, .low = 0x%016llxULL, .high = 0x%016llxULL},\n",
          enumerator, static_cast<unsigned long long>(seed), len, static_cast<unsigned long long>(low),
          static_cast<unsigned long long>(high));
    }
  }
}

}  // namespace

int main() {
  const std::size_t count = 3 * kLens.size() * kSeeds.size();
  std::fputs(
      mbo::strings::DropIndent(R"cc(
        // GENERATED by //mbo/hash:hash_test_vectors_gen -- DO NOT EDIT BY HAND.
        //
        // Known-answer vectors for the in-house mumbo/jumbo and dumbo hashes, pinned
        // at their CURRENT output. NOT stable across library versions (the -umbo
        // family is still evolving pre-1.0); regenerate INTENTIONALLY on an algorithm
        // change (and refresh hash_test_vectors.inc.sha256), then review the diff:
        //   bazel run //mbo/hash:hash_test_vectors_gen > mbo/hash/hash_test_vectors.inc
        //   bazel run //mbo/digest:digest -- -a sha256 mbo/hash/hash_test_vectors.inc \
        //       > mbo/hash/hash_test_vectors.inc.sha256
        // hash_test.cc verifies each vector against the live algorithm; the committed
        // .sha256 is the independently verifiable integrity check. Inputs are the
        // deterministic PatternBuffer(len) (byte i = (i*131+7) % 256); seeds 0 and
        // 5381; lengths span the small-key, chain, and bulk dispatch tiers. `low` is
        // the 64-bit hash (or h1 of the 128-bit hash); `high` is h2 (0 for 64-bit).

        namespace mbo::hash::kat {

        enum class Algo { kMumbo, kJumbo, kDumbo };

        struct Vector {
          Algo algo;
          std::uint64_t seed;
          std::size_t len;
          std::uint64_t low;
          std::uint64_t high;
        };
      )cc")
          .c_str(),
      stdout);

  std::printf("\ninline constexpr std::array<Vector, %zu> kVectors{{\n", count);
  EmitAlgo("kMumbo", 0);
  EmitAlgo("kJumbo", 1);
  EmitAlgo("kDumbo", 2);
  std::printf("}};\n\n");
  std::printf("}  // namespace mbo::hash::kat\n");
  return 0;
}

// NOLINTEND(*-vararg,cert-err33-c,*-magic-numbers)
