#!/usr/bin/env python3
"""Tests for tools/coverage_html.py."""

import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import coverage_html


_HEADER = """<html><head></head><body>
          <table width="100%" border=0 cellspacing=0 cellpadding=0>
            <tr><td class="title">LCOV - code coverage report</td></tr>
            <tr><td class="ruler"><img src="{prefix}glass.png" width=3 height=3 alt=""></td></tr>
            <tr><td><table><tr><td>Coverage table</td></tr></table></td></tr>
            <tr><td class="ruler"><img src="{prefix}glass.png" width=3 height=3 alt=""></td></tr>
          </table>
          <center>
            <table id="detail"><tr><td>Report content</td></tr></table>
          </center>
          <table id="footer"><tr><td class="versionInfo">Generated by LCOV</td></tr></table>
</body></html>
"""


class CoverageHtmlTest(unittest.TestCase):
    def setUp(self):
        self.policy = {
            "minimum": {"lines": 90, "functions": 95, "branches": 80},
            "target": {"lines": 92, "functions": 95, "branches": 82},
            "enforce": "medium",
        }

    def test_moves_policy_matrix_below_detail_table_and_adds_root_navigation(self):
        with tempfile.TemporaryDirectory() as directory:
            report = Path(directory)
            page = report / "index.html"
            page.write_text(_HEADER.format(prefix=""), encoding="utf-8")
            coverage_html.apply(report, self.policy, "pr/635")
            rendered = page.read_text(encoding="utf-8")
            self.assertIn('<a href="../index.html">Report overview</a>', rendered)
            self.assertIn('<a href="../../../index.html">All coverage reports</a>', rendered)
            self.assertLess(rendered.index("mboNavigation"), rendered.index("Coverage table"))
            self.assertLess(rendered.index('id="detail"'), rendered.index("Global coverage policy"))
            self.assertLess(rendered.index("Global coverage policy"), rendered.index('id="footer"'))
            self.assertIn('<th scope="col">Low</th>', rendered)
            self.assertIn('<th scope="col">Medium</th>', rendered)
            self.assertIn('<th scope="col">High</th>', rendered)
            self.assertIn('<th scope="col">Enforced</th>', rendered)
            self.assertIn('<td class="headerValueLegL">&lt; 90%</td>', rendered)
            self.assertIn('<td class="headerValueLegM">&ge; 80% and &lt; 82%</td>', rendered)
            self.assertIn('<td class="headerValueLegH">&ge; 82%</td>', rendered)
            self.assertIn('<th scope="row">Functions</th>', rendered)
            self.assertIn('<td class="headerValueLegM">-</td>', rendered)
            self.assertEqual(3, rendered.count('<td class="headerValueLegM">Medium</td>'))
            self.assertLess(rendered.index('<th scope="row">Lines</th>'), rendered.index('<th scope="row">Branches</th>'))
            self.assertLess(
                rendered.index('<th scope="row">Branches</th>'), rendered.index('<th scope="row">Functions</th>')
            )
            self.assertIn(".mboNavigation { padding: .35rem 0; text-align: center; }", rendered)
            self.assertIn(".mboPolicy { border-collapse: collapse; margin: .75rem auto 1rem; width: auto; }", rendered)
            self.assertIn(".mboPolicy td { font-size: 100%; padding: .2rem .75rem; text-align: center; }", rendered)

    def test_normalizes_header_and_table_percentage_colors_per_metric(self):
        source = """<tr><td class="headerItem">Lines:</td><td class="headerCovTableEntryHi">91.0&nbsp;%</td></tr>
<tr><td class="headerItem">Functions:</td><td class="headerCovTableEntryLo">93.0&nbsp;%</td></tr>
<tr><td class="headerItem">Branches:</td><td class="headerCovTableEntryHi">92.0&nbsp;%</td></tr>
<td class="coverPerHi">91.0&nbsp;%</td><td class="coverPerHi">92.0&nbsp;%</td><td class="coverPerLo">93.0&nbsp;%</td>
<td class="coverPerHi">96.0&nbsp;%</td><td class="coverPerHi">-</td><td class="coverPerHi">93.0&nbsp;%</td>"""
        rendered = coverage_html._normalize_rate_classes(source, self.policy)
        self.assertIn('headerCovTableEntryMed">91.0', rendered)
        self.assertIn('headerCovTableEntryLo">93.0', rendered)
        self.assertIn('headerCovTableEntryHi">92.0', rendered)
        self.assertIn('coverPerMed">91.0', rendered)
        self.assertIn('coverPerHi">92.0', rendered)
        self.assertIn('coverPerLo">93.0', rendered)
        self.assertIn('coverPerHi">-</td>', rendered)
        self.assertEqual(2, rendered.count('coverPerLo">93.0'))

    def test_normalizes_a_directory_table_without_branch_data(self):
        source = """>Line Coverage</td><td>Function Coverage</td>
<td class="coverPerHi">91.0&nbsp;%</td><td class="coverPerHi">94.0&nbsp;%</td>
<td class="coverPerHi">93.0&nbsp;%</td><td class="coverPerHi">96.0&nbsp;%</td>"""
        rendered = coverage_html._normalize_rate_classes(source, self.policy)
        self.assertEqual(1, rendered.count('coverPerMed">91.0'))
        self.assertEqual(1, rendered.count('coverPerLo">94.0'))
        self.assertEqual(1, rendered.count('coverPerHi">93.0'))
        self.assertEqual(1, rendered.count('coverPerHi">96.0'))

    def test_constrains_header_summary_to_detail_table_width(self):
        with tempfile.TemporaryDirectory() as directory:
            report = Path(directory)
            page = report / "index.html"
            page.write_text(
                _HEADER.replace(
                    '<tr><td><table><tr><td>Coverage table</td></tr></table></td></tr>',
                    '<tr><td width="100%"><table cellpadding=1 border=0 width="100%"><tr><td>Totals</td></tr></table></td></tr>',
                ).format(prefix=""),
                encoding="utf-8",
            )
            coverage_html.apply(report, self.policy, "main")
            rendered = page.read_text(encoding="utf-8")
            self.assertIn('<table class="mboHeaderSummary" cellpadding=1 border=0>', rendered)
            self.assertIn(".mboHeaderSummary { margin: 0 auto; width: 80%; }", rendered)

    def test_nested_page_links_reach_the_same_overview_and_index(self):
        with tempfile.TemporaryDirectory() as directory:
            report = Path(directory)
            page = report / "program" / "mbo" / "source.gcov.html"
            page.parent.mkdir(parents=True)
            page.write_text(_HEADER.format(prefix="../../"), encoding="utf-8")
            coverage_html.apply(report, self.policy, "main")
            rendered = page.read_text(encoding="utf-8")
            self.assertIn('<a href="../../../index.html">Report overview</a>', rendered)
            self.assertIn('<a href="../../../../index.html">All coverage reports</a>', rendered)

    def test_reprocessing_is_idempotent(self):
        with tempfile.TemporaryDirectory() as directory:
            report = Path(directory)
            page = report / "index.html"
            page.write_text(_HEADER.format(prefix=""), encoding="utf-8")
            coverage_html.apply(report, self.policy, "main")
            coverage_html.apply(report, self.policy, "main")
            rendered = page.read_text(encoding="utf-8")
            self.assertEqual(1, rendered.count('class="mboNavigation"'))
            self.assertEqual(1, rendered.count('class="mboPolicy"'))
            self.assertEqual(1, rendered.count("Global coverage policy"))
            self.assertEqual(1, rendered.count(".mboNavigation"))

    def test_rejects_an_unrecognized_genhtml_page(self):
        with tempfile.TemporaryDirectory() as directory:
            page = Path(directory) / "index.html"
            page.write_text("not a genhtml page", encoding="utf-8")
            with self.assertRaisesRegex(ValueError, "header anchors not found"):
                coverage_html.apply(Path(directory), self.policy, "main")

    def test_rejects_an_unsafe_target(self):
        with tempfile.TemporaryDirectory() as directory:
            with self.assertRaisesRegex(ValueError, "invalid coverage target"):
                coverage_html.apply(Path(directory), self.policy, "../main")


if __name__ == "__main__":
    unittest.main()
