name: pr
on:
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bazel cache
        id: bazel-cache
        uses: actions/cache@v2
        env:
          version: 4.2.1
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-{{ env.version }}-bazel-cache

      - name: Test OPT
        run: bazel build //... -c opt

      - name: Test ASAN
        run: bazel build //... --config=asan -c dbg
