name: Test

on: [push]

jobs:
    checks:
        name: Test
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: bazelbuild/setup-bazelisk@v2
        - name: Test OPT
          run: bazel build //... -c opt
        - name: Test ASAN
          run: bazel build //... --config=asan -c dbg
