name: Test
on: [push]
jobs:
  test-clang-asan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bazel cache
        id: bazel-cache
        uses: actions/cache@v2
        env:
          version: 4.2.1
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
            ~/.cache/bazel-cache
          key: ${{ runner.os }}-${{ env.version }}-bazel-cache-clang-asan

      - name: Test Clang/ASAN
        run: |
          bazel test --config=clang --config=asan -c dbg //...

  test-clang-opt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bazel cache
        id: bazel-cache
        uses: actions/cache@v2
        env:
          version: 4.2.1
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
            ~/.cache/bazel-cache
          key: ${{ runner.os }}-${{ env.version }}-bazel-cache-clang-opt

      - name: Test Clang/OPT
        run: |
          bazel test --config=clang -c opt //...

  test-gcc-fastbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bazel cache
        id: bazel-cache
        uses: actions/cache@v2
        env:
          version: 4.2.1
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
            ~/.cache/bazel-cache
          key: ${{ runner.os }}-${{ env.version }}-bazel-cache-gcc-fastbuild

      - name: Test GCC/Fastbuild
        run: |
          CC=gcc bazel test -c fastbuild //...
