name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bazel cache
        id: bazel-cache
        uses: actions/cache@v2
        env:
          version: 4.2.1
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-{{ env.version }}-bazel-cache

      - name: Test Clang/ASAN
        run: |
          bazel test --config=clang --config=asan -c dbg //...

      - name: Test Clang/OPT
        run: |
          bazel test --config=clang -c opt //...

      - name: Test GCC/Fastbuild
        run: |
          CC=gcc bazel test -c fastbuild //...
