name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bazel cache
        id: bazel-cache
        uses: actions/cache@v2
        env:
          version: 4.2.1
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-{{ env.version }}-bazel-cache

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "17.0"

      - name: Test Clang
        run: |
          ${LLVM_PATH}/bin/clang-format --version
          clang-format --version
          which clang-format
          bazel build //mbo/types/internal:decompose_count_test || bazel build //mbo/types/internal:decompose_count_test --sandbox_debug -s

      - name: Test OPT
        run: |
          echo "${GITHUB_WORKSPACE}"
          cd "${GITHUB_WORKSPACE}" && bazel build //... -c opt

      - name: Test ASAN
        run: |
          cd "${GITHUB_WORKSPACE}" && bazel build //... --config=asan -c dbg
