name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bazel cache
        id: bazel-cache
        uses: actions/cache@v2
        env:
          version: 4.2.1
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-{{ env.version }}-bazel-cache

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "17.0"

      - name: Test OPT
        run: |
          bazel build --//mbo/mope:clang_format="${LLVM_PATH}/bin/clang-format" //... -c opt 

      - name: Test ASAN
        run: |
          bazel build --//mbo/mope:clang_format="${LLVM_PATH}/bin/clang-format" //... --config=asan -c dbg
