name: Test
on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - uses: pre-commit/action@v3.0.1
      - uses: pre-commit-ci/lite-action@v1.0.2
        if: always()

  test-gcc:
    needs: pre-commit
    strategy:
      matrix:
        os: [ubuntu-latest]
        bazel_mode: [bzlmod]
        compiler: [gcc]
        gcc_version: [11, 12, 13]
        bazel_config: [opt]

    uses: ./.github/workflows/test.yml
    with:
      os: ${{ matrix.os }}
      bazel_mode: ${{ matrix.bazel_mode }}
      compiler: ${{ matrix.compiler }}
      gcc_version: ${{ matrix.gcc_version }}
      bazel_config: ${{ matrix.bazel_config }}

  test-clang:
    needs: [pre-commit, test-gcc]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        bazel_mode: [bzlmod]
        compiler: [clang]
        llvm_version: [19.1.6, 17.0.4]
        bazel_config: [asan, opt, fastbuild]
        exclude:
          - os: macos-latest
            bazel_config: asan
          - os: macos-latest
            bazel_config: fastbuild
          - llvm_version: 17.0.4
            bazel_config: asan
          - llvm_version: 17.0.4
            bazel_config: fastbuild

    uses: ./.github/workflows/test.yml
    with:
      continue-on-error: true
      os: ${{ matrix.os }}
      bazel_mode: ${{ matrix.bazel_mode }}
      compiler: ${{ matrix.compiler }}
      llvm_version: ${{ matrix.llvm_version }}
      bazel_config: ${{ matrix.bazel_config }}

  test-bcr:
    needs: [pre-commit, test-gcc, test-clang]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        bazel_mode: [bzlmod]
        compiler: [clang]
        llvm_version: [19.1.6]
        bazel_config: [opt]
        module_versions: [0.4.2]

    uses: ./.github/workflows/test.yml
    with:
      continue-on-error: true
      os: ${{ matrix.os }}
      bazel_mode: ${{ matrix.bazel_mode }}
      compiler: ${{ matrix.compiler }}
      llvm_version: ${{ matrix.llvm_version }}
      bazel_config: ${{ matrix.bazel_config }}
