name: Test
on: [push]
jobs:
  test-clang-asan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v3

      - name: Bazel cache
        uses: actions/cache@v4
        with:
            path: "~/.cache/bazel"
            key: bazel-cache-clang-asan

      - name: Test Clang/ASAN
        run: |
          bazel test --config=clang --config=asan -c dbg //...

  test-clang-opt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v3

      - name: Bazel cache
        uses: actions/cache@v4
        with:
            path: "~/.cache/bazel"
            key: bazel-cache-clang-opt

      - name: Test Clang/OPT
        run: |
          bazel test --config=clang -c opt //...

  test-gcc-fastbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v3

      - name: Bazel cache
        uses: actions/cache@v4
        with:
            path: "~/.cache/bazel"
            key: bazel-cache-gcc-fastbuild

      - name: Test GCC/Fastbuild
        run: |
          CC=gcc bazel test -c fastbuild //...
