name: Test
on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - uses: pre-commit/action@v3.0.1
      - uses: pre-commit-ci/lite-action@v1.0.2
        if: always()

  test-gcc:
    needs: pre-commit
    secrets: inherit
    strategy:
      matrix:
        os: [ubuntu-latest]
        bazel_mode: [bzlmod, workspace]
        compiler: [gcc]
        gcc_version: [13, 14]
        bazel_config: [cpp23, opt]
        exclude:
          - bazel_mode: workspace
            gcc_version: 14
          - bazel_config: cpp23
            gcc_version: 13

    uses: ./.github/workflows/test.yml
    with:
      continue-on-error: true
      os: ${{ matrix.os }}
      bazel_mode: ${{ matrix.bazel_mode }}
      compiler: ${{ matrix.compiler }}
      gcc_version: ${{ matrix.gcc_version }}
      bazel_config: ${{ matrix.bazel_config }}

  test-clang:
    needs: [pre-commit, test-gcc]
    secrets: inherit
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        bazel_mode: [bzlmod]
        compiler: [clang]
        llvm_version: [17.0.4, 19.1.6, 20.1.0]
        bazel_config: [asan, cpp23, fastbuild, opt]
        exclude:
          - os: macos-latest
            bazel_config: asan
          - os: macos-latest
            bazel_config: cpp23
          - os: macos-latest
            bazel_config: fastbuild
          - os: macos-latest
            llvm_version: 20.1.0
          - llvm_version: 17.0.4
            bazel_config: asan
          - llvm_version: 17.0.4
            bazel_config: cpp23
          - llvm_version: 17.0.4
            bazel_config: fastbuild
          - llvm_version: 20.1.0
            bazel_config: asan
          - llvm_version: 20.1.0
            bazel_config: fastbuild

    uses: ./.github/workflows/test.yml
    with:
      continue-on-error: true
      os: ${{ matrix.os }}
      bazel_mode: ${{ matrix.bazel_mode }}
      compiler: ${{ matrix.compiler }}
      llvm_version: ${{ matrix.llvm_version }}
      bazel_config: ${{ matrix.bazel_config }}

  test-bcr:
    needs: [pre-commit, test-gcc]
    secrets: inherit
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        bazel_mode: [bzlmod]
        compiler: [gcc, native]
        gcc_version: [13]
        llvm_version: [17.0.4]
        bazel_config: [opt]
        module_version: [0.6.0]
        exclude:
          - os: ubuntu-latest
            compiler: native
          - os: macos-latest
            compiler: gcc

    uses: ./.github/workflows/test.yml
    with:
      continue-on-error: true
      os: ${{ matrix.os }}
      bazel_mode: ${{ matrix.bazel_mode }}
      compiler: ${{ matrix.compiler }}
      gcc_version: ${{ matrix.gcc_version }}
      llvm_version: ${{ matrix.llvm_version }}
      bazel_config: ${{ matrix.bazel_config }}
      module_version: ${{ matrix.module_version }}

  done:
    needs: [pre-commit, test-gcc, test-clang, test-bcr]
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: echo "Done"
